trigger:
  batch: true
  branches:
    include:
    - master
    - ?.?*  # matches to backport branches, e.g. 3.6
  tags:
    exclude:
    - '*'
pr:
  autoCancel: true
  branches:
    include:
    - master
    - ?.?*  # matches to backport branches, e.g. 3.6

variables:
- group: codecov

resources:
  containers:
  - container: manylinux
    image: quay.io/pypa/manylinux1_x86_64
  repositories:
  - repository: templates
    type: github
    name: Dish1306/azure-pipelines
    endpoint: aio-libs

stages:
- template: stage-lint.yml
- template: stage-test.yml
- template: stage-test-aarch64.yml
